"use client";

import { CardProps } from "../../components/Cards/CardList";

export const myCards: CardProps[] = [
    {
        id: "card-1",
        title: "Next.js Card",
        description: "This is a custom card with props.",
        imageSrc: "/next.svg",
    },
    {
        id: "card-2",
        title: "Dark Mode Card",
        description: "A card with a dark background.",
        imageSrc: "/vercel.svg",
    },
    {
        id: "card-3",
        title: "React Card",
        description: "A card showcasing React features.",
        imageSrc: "/react.svg",
    },
    {
        id: "card-4",
        title: "TypeScript Card",
        description: "A card highlighting TypeScript benefits.",
        imageSrc: "/typescript.svg",
    },
    {
        id: "card-5",
        title: "Tailwind CSS Card",
        description: "A card styled with Tailwind CSS.",
        imageSrc: "/tailwind.svg",
    },
    {
        id: "card-6",
        title: "GraphQL Card",
        description: "A card about GraphQL APIs.",
        imageSrc: "/graphql.svg",
    },
    {
        id: "card-7",
        title: "Node.js Card",
        description: "A card about Node.js runtime.",
        imageSrc: "/node.svg",
    },
    {
        id: "card-8",
        title: "Angular Card",
        description: "A card showcasing Angular framework.",
        imageSrc: "/angular.svg",
    },
    {
        id: "card-9",
        title: "Vue.js Card",
        description: "A card about Vue.js framework.",
        imageSrc: "/vue.svg",
    },
    {
        id: "card-10",
        title: "Svelte Card",
        description: "A card highlighting Svelte features.",
        imageSrc: "/svelte.svg",
    },
    {
        id: "card-11",
        title: "Python Card",
        description: "A card about Python programming.",
        imageSrc: "/python.svg",
    },
    {
        id: "card-12",
        title: "Django Card",
        description: "A card showcasing Django framework.",
        imageSrc: "/django.svg",
    },
    {
        id: "card-13",
        title: "Flask Card",
        description: "A card about Flask microframework.",
        imageSrc: "/flask.svg",
    },
    {
        id: "card-14",
        title: "Ruby on Rails Card",
        description: "A card about Ruby on Rails.",
        imageSrc: "/rails.svg",
    },
    {
        id: "card-15",
        title: "Java Card",
        description: "A card about Java programming.",
        imageSrc: "/java.svg",
    },
    {
        id: "card-16",
        title: "Spring Boot Card",
        description: "A card showcasing Spring Boot.",
        imageSrc: "/spring.svg",
    },
    {
        id: "card-17",
        title: "Kotlin Card",
        description: "A card about Kotlin programming.",
        imageSrc: "/kotlin.svg",
    },
    {
        id: "card-18",
        title: "Swift Card",
        description: "A card about Swift programming.",
        imageSrc: "/swift.svg",
    },
    {
        id: "card-19",
        title: "Flutter Card",
        description: "A card showcasing Flutter framework.",
        imageSrc: "/flutter.svg",
    },
    {
        id: "card-20",
        title: "Dart Card",
        description: "A card about Dart programming.",
        imageSrc: "/dart.svg",
    },
    {
        id: "card-21",
        title: "Go Card",
        description: "A card about Go programming.",
        imageSrc: "/go.svg",
    },
    {
        id: "card-22",
        title: "Rust Card",
        description: "A card about Rust programming.",
        imageSrc: "/rust.svg",
    },
    {
        id: "card-23",
        title: "C++ Card",
        description: "A card about C++ programming.",
        imageSrc: "/cpp.svg",
    },
    {
        id: "card-24",
        title: "C# Card",
        description: "A card about C# programming.",
        imageSrc: "/csharp.svg",
    },
    {
        id: "card-25",
        title: "PHP Card",
        description: "A card about PHP programming.",
        imageSrc: "/php.svg",
    },
    {
        id: "card-26",
        title: "Laravel Card",
        description: "A card showcasing Laravel framework.",
        imageSrc: "/laravel.svg",
    },
    {
        id: "card-27",
        title: "Bootstrap Card",
        description: "A card styled with Bootstrap.",
        imageSrc: "/bootstrap.svg",
    },
    {
        id: "card-28",
        title: "Webpack Card",
        description: "A card about Webpack bundler.",
        imageSrc: "/webpack.svg",
    },
    {
        id: "card-29",
        title: "Babel Card",
        description: "A card about Babel transpiler.",
        imageSrc: "/babel.svg",
    },
    {
        id: "card-30",
        title: "ESLint Card",
        description: "A card about ESLint for linting.",
        imageSrc: "/eslint.svg",
    },
];
