"use client";

// import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/components/Navbar/Header";
import LeftSide from "@/components/Navbar/LeftSide";
import MarginWidthWrapper from "@/components/Navbar/marginWithWrapper";
import PageWrapper from "@/components/Navbar/PageWrapper";
import HeaderMobile from "@/components/Navbar/HeaderMobile";
import { Provider } from "react-redux";
import { store } from "@/redux/store";
import ThemeProvider from "./theme-provider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata: Metadata = {
//   title: "Chart Crafter",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressContentEditableWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-white dark:bg-[#191919] text-[#37352f] dark:text-[#ffffffcf]`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <Provider store={store}>
            <div className="flex">
              <div className="print:hidden">
                <LeftSide />
              </div>
              <main className="flex-1 ">
                <MarginWidthWrapper>
                  <div className="print:hidden sticky top-0 z-50 bg-white">
                    <Header />
                  </div>
                  <div className="print:hidden">
                    <HeaderMobile />
                  </div>
                  <PageWrapper>{children}</PageWrapper>
                </MarginWidthWrapper>
              </main>
            </div>
          </Provider>
        </ThemeProvider>
      </body>
    </html>
  );
}
